"""initial migration

Revision ID: 80be21b706c0
Revises: 
Create Date: 2026-07-16 11:14:36.016849

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80be21b706c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('vehicle_type', sa.Enum('jeepney', 'modern_jeepney', 'tricycle', 'pedicab', 'taxi', 'ride_hailing_car', 'ride_hailing_motorcycle', 'mrt', 'lrt', 'pnr', 'bus', 'provincial_bus', 'uv_express', 'multicab', 'kalesa', 'habal_habal', 'motorela', 'rail_trolley', 'ferry', 'fast_craft', 'roro', 'pump_boat', 'passenger_ship', 'domestic_flight', 'walking', 'bicycle', name='vehicle_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', 'deprecated', name='route_status'), server_default='pending', nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('path', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_routes_path', 'routes', ['path'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_routes_created_at'), 'routes', ['created_at'], unique=False)
    op.create_index(op.f('ix_routes_deleted_at'), 'routes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=False)
    op.create_index(op.f('ix_routes_status'), 'routes', ['status'], unique=False)
    op.create_index(op.f('ix_routes_updated_at'), 'routes', ['updated_at'], unique=False)
    op.create_index(op.f('ix_routes_vehicle_type'), 'routes', ['vehicle_type'], unique=False)
    op.create_table('stops',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('stop_type', sa.Enum('standard', 'terminal', 'spur_stop', 'interchange', 'port', 'airport', name='stop_type'), server_default='standard', nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('barangay', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stops_location', 'stops', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_stops_barangay'), 'stops', ['barangay'], unique=False)
    op.create_index(op.f('ix_stops_city'), 'stops', ['city'], unique=False)
    op.create_index(op.f('ix_stops_created_at'), 'stops', ['created_at'], unique=False)
    op.create_index(op.f('ix_stops_deleted_at'), 'stops', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_stops_name'), 'stops', ['name'], unique=False)
    op.create_index(op.f('ix_stops_stop_type'), 'stops', ['stop_type'], unique=False)
    op.create_index(op.f('ix_stops_updated_at'), 'stops', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('role', sa.Enum('contributor', 'trusted_contributor', 'moderator', 'administrator', name='user_role'), server_default='contributor', nullable=False),
    sa.Column('rank', sa.Enum('mortal_traveler', 'path_seeker', 'route_disciple', 'map_adept', 'transit_master', 'grand_cartographer', 'arch_navigator', 'celestial_pathfinder', 'mythic_wayfinder', 'galaeros_immortal', name='contributor_rank'), server_default='mortal_traveler', nullable=False),
    sa.Column('experience_points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trust_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_rank'), 'users', ['rank'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_trust_score'), 'users', ['trust_score'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_table('route_stops',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('stop_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('fare_to_next_stop', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('distance_meters_to_next_stop', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence', name='uq_route_stop_sequence')
    )
    op.create_index(op.f('ix_route_stops_created_at'), 'route_stops', ['created_at'], unique=False)
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_stops_sequence'), 'route_stops', ['sequence'], unique=False)
    op.create_index(op.f('ix_route_stops_stop_id'), 'route_stops', ['stop_id'], unique=False)
    op.create_index(op.f('ix_route_stops_updated_at'), 'route_stops', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stops_updated_at'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_stop_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_sequence'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_created_at'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_trust_score'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_rank'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stops_updated_at'), table_name='stops')
    op.drop_index(op.f('ix_stops_stop_type'), table_name='stops')
    op.drop_index(op.f('ix_stops_name'), table_name='stops')
    op.drop_index(op.f('ix_stops_deleted_at'), table_name='stops')
    op.drop_index(op.f('ix_stops_created_at'), table_name='stops')
    op.drop_index(op.f('ix_stops_city'), table_name='stops')
    op.drop_index(op.f('ix_stops_barangay'), table_name='stops')
    op.drop_index('idx_stops_location', table_name='stops', postgresql_using='gist')
    op.drop_table('stops')
    op.drop_index(op.f('ix_routes_vehicle_type'), table_name='routes')
    op.drop_index(op.f('ix_routes_updated_at'), table_name='routes')
    op.drop_index(op.f('ix_routes_status'), table_name='routes')
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_index(op.f('ix_routes_deleted_at'), table_name='routes')
    op.drop_index(op.f('ix_routes_created_at'), table_name='routes')
    op.drop_index('idx_routes_path', table_name='routes', postgresql_using='gist')
    op.drop_table('routes')
    # ### end Alembic commands ###
